/**
 * Service for fetching Amazon EC2 and Amazon ECS pricing data
 * 
 * This service loads comprehensive EC2 pricing data from a pre-generated JSON file.
 * The pricing data covers all AWS regions and 700+ instance types.
 * 
 * Pricing Strategy:
 * 1. Load pricing from /data/ec2-prices.json (generated by scripts/generate-pricing-data.js)
 * 2. If file not available, fall back to calculated estimates
 * 
 * To update pricing:
 * Run: npm run update-pricing
 * This regenerates the pricing data file with current prices.
 */

// In-memory cache for pricing data
const pricingCache = {
    ec2: {},
    pricingData: null,
    loadPromise: null,
    lastUpdated: null
};

/**
 * Loads pricing data from the JSON file.
 * @returns {Promise<Object|null>} - Pricing data object or null on failure
 */
const loadPricingData = () => {
    if (pricingCache.pricingData) {
        return Promise.resolve(pricingCache.pricingData);
    }

    if (pricingCache.loadPromise) {
        return pricingCache.loadPromise;
    }

    pricingCache.loadPromise = fetch('/data/ec2-prices.json')
        .then(response => {
            if (!response.ok) {
                console.warn('Pricing data file not found, using fallback estimates');
                return null;
            }
            return response.json();
        })
        .then(data => {
            if (data) {
                pricingCache.pricingData = data;
                pricingCache.lastUpdated = data.metadata.generatedAt;
                console.log(`Loaded pricing data: ${data.metadata.totalInstanceTypes} instance types across ${data.metadata.totalRegions} regions`);
            }
            return data;
        })
        .catch(error => {
            console.warn('Error loading pricing data file, using fallback estimates:', error.message);
            pricingCache.loadPromise = null; // Allow retry on failure
            return null;
        });

    return pricingCache.loadPromise;
};

/**
 * Gets EC2 pricing for a specific region and instance type
 * @param {string} region - AWS region code
 * @param {string} instanceType - EC2 instance type
 * @returns {Promise<number>} - Hourly price for the instance type
 */
export const getEC2Price = async (region, instanceType) => {
    // Check if we have cached data for this region and instance
    const cacheKey = `${region}-${instanceType}`;
    if (pricingCache.ec2[cacheKey] !== undefined) {
        return pricingCache.ec2[cacheKey];
    }

    try {
        // Try to load pricing data from JSON file
        const pricingData = await loadPricingData();
        let price = null;
        
        if (pricingData && pricingData.regions[region] && pricingData.regions[region].prices[instanceType]) {
            // Use price from loaded data
            price = pricingData.regions[region].prices[instanceType];
        } else {
            // Fall back to estimation
            if (pricingData && !pricingData.regions[region]) {
                console.warn(`Region ${region} not in pricing data, using estimation`);
            } else if (pricingData) {
                console.warn(`Instance type ${instanceType} not found in ${region}, using estimation`);
            }
            price = estimatePriceWithRegionalMultiplier(region, instanceType);
        }
        
        pricingCache.ec2[cacheKey] = price;
        return price;
    } catch (error) {
        console.error(`Error fetching EC2 price for ${instanceType} in ${region}:`, error);
        const estimatedPrice = estimatePriceWithRegionalMultiplier(region, instanceType);
        pricingCache.ec2[cacheKey] = estimatedPrice;
        return estimatedPrice;
    }
};

/**
 * Estimates price for an instance type in a region using regional multiplier
 * @param {string} region - AWS region code
 * @param {string} instanceType - EC2 instance type
 * @returns {number} - Estimated hourly price
 */
const estimatePriceWithRegionalMultiplier = (region, instanceType) => {
    const [family, size] = instanceType.split('.');
    const basePrice = estimateInstancePrice(family, size);
    const regionalMultiplier = getRegionalPriceMultiplier(region);
    return parseFloat((basePrice * regionalMultiplier).toFixed(5));
};

/**
 * Estimates price for an instance type based on family and size
 * @param {string} family - Instance family
 * @param {string} size - Instance size
 * @returns {number} - Estimated hourly price
 */
const estimateInstancePrice = (family, size) => {
    // Base prices for 'large' size instances in us-east-1
    const familyBasePrices = {
        // General Purpose
        't3': 0.0832, 't3a': 0.0752, 't4g': 0.0672,
        'm5': 0.096, 'm5a': 0.086, 'm5ad': 0.103, 'm5d': 0.113, 'm5dn': 0.136, 'm5n': 0.119, 'm5zn': 0.1534,
        'm6a': 0.0864, 'm6g': 0.077, 'm6gd': 0.0923, 'm6i': 0.096, 'm6id': 0.1152, 'm6idn': 0.1389, 'm6in': 0.1195,
        'm7a': 0.0907, 'm7g': 0.0816, 'm7gd': 0.0979, 'm7i': 0.1008, 'm7i-flex': 0.1008,
        'm8g': 0.0864, 'm8gd': 0.1037,
        
        // Compute Optimized
        'c5': 0.085, 'c5a': 0.077, 'c5ad': 0.086, 'c5d': 0.096, 'c5n': 0.108,
        'c6a': 0.0765, 'c6g': 0.068, 'c6gd': 0.0816, 'c6i': 0.085, 'c6id': 0.1008, 'c6in': 0.1062,
        'c7a': 0.0803, 'c7g': 0.0725, 'c7gd': 0.087, 'c7gn': 0.0906, 'c7i': 0.0893, 'c7i-flex': 0.0893,
        'c8g': 0.0768, 'c8gd': 0.0922, 'c8gn': 0.0960,
        'hpc6a': 0.99, 'hpc6id': 1.10, 'hpc7a': 0.88,
        
        // Memory Optimized
        'r5': 0.126, 'r5a': 0.113, 'r5ad': 0.131, 'r5b': 0.151, 'r5d': 0.144, 'r5dn': 0.169, 'r5n': 0.149,
        'r6a': 0.1134, 'r6g': 0.1008, 'r6gd': 0.1210, 'r6i': 0.126, 'r6id': 0.1512, 'r6idn': 0.1823, 'r6in': 0.1567,
        'r7a': 0.1190, 'r7g': 0.1075, 'r7gd': 0.1290, 'r7i': 0.1323, 'r7iz': 0.1587,
        'r8g': 0.1139, 'r8gd': 0.1367,
        'u-3tb1': 109.20, 'u7i-6tb': 218.40, 'u7i-8tb': 291.20, 'u7i-12tb': 436.80, 'u7in-24tb': 873.60, 'u7in-32tb': 1164.80,
        'x2gd': 0.668, 'x2idn': 1.668, 'x2iedn': 1.668, 'x2iezn': 2.084, 'x8g': 0.7084,
        'z1d': 0.186,
        
        // Storage Optimized
        'd3': 0.149, 'd3en': 0.251,
        'i4g': 0.390, 'i4i': 0.390, 'i7i': 0.413, 'i7ie': 0.413, 'i8g': 0.437,
        'im4gn': 0.390, 'is4gen': 0.390,
        
        // Accelerated Computing
        'g4dn': 0.526, 'g5': 1.006, 'g5g': 0.420, 'g6': 0.826, 'g6e': 1.652, 'g6f': 0.826,
        'gr6': 1.652, 'gr6f': 0.826,
        'p3dn': 31.218, 'p4d': 32.773, 'p5': 98.32, 'p6-b200': 120.00
    };

    const sizeMultipliers = {
        'nano': 0.0625, 'micro': 0.125, 'small': 0.25, 'medium': 0.5, 'large': 1.0,
        'xlarge': 2.0, '2xlarge': 4.0, '3xlarge': 6.0, '4xlarge': 8.0, '6xlarge': 12.0,
        '8xlarge': 16.0, '9xlarge': 18.0, '12xlarge': 24.0, '16xlarge': 32.0, '18xlarge': 36.0,
        '24xlarge': 48.0, '32xlarge': 64.0, '48xlarge': 96.0, '56xlarge': 112.0, '96xlarge': 192.0,
        '112xlarge': 224.0, '224xlarge': 448.0
    };

    const basePrice = familyBasePrices[family] || 0.096; // Default to m5.large price
    const multiplier = sizeMultipliers[size] || 1.0;

    return basePrice * multiplier;
};

/**
 * Gets price multiplier for a region relative to us-east-1
 * @param {string} region - AWS region code
 * @returns {number} - Price multiplier
 */
const getRegionalPriceMultiplier = (region) => {
    const multipliers = {
        'us-east-1': 1.0,
        'us-east-2': 1.0,
        'us-west-1': 1.21,
        'us-west-2': 1.0,
        'ca-central-1': 1.08,
        'sa-east-1': 1.35,
        'eu-west-1': 1.12,
        'eu-west-2': 1.18,
        'eu-west-3': 1.18,
        'eu-central-1': 1.15,
        'eu-central-2': 1.17,
        'eu-north-1': 1.08,
        'eu-south-1': 1.16,
        'eu-south-2': 1.16,
        'ap-northeast-1': 1.25,
        'ap-northeast-2': 1.18,
        'ap-northeast-3': 1.25,
        'ap-southeast-1': 1.22,
        'ap-southeast-2': 1.22,
        'ap-southeast-3': 1.23,
        'ap-southeast-4': 1.23,
        'ap-south-1': 1.15,
        'ap-south-2': 1.16,
        'ap-east-1': 1.25,
        'me-south-1': 1.20,
        'me-central-1': 1.21,
        'af-south-1': 1.25,
        'il-central-1': 1.19
    };

    return multipliers[region] || 1.0;
};

/**
 * Gets ECS pricing
 * @returns {Object} - ECS pricing information
 */
export const getECSPricing = () => {
    return {
        managementFeePerInstance: 0.01 // $0.01 per instance per hour
    };
};

/**
 * Checks if an instance type is available in a region
 * @param {string} region - AWS region code
 * @param {string} instanceType - EC2 instance type
 * @returns {Promise<boolean>} - Whether the instance type is available
 */
export const isInstanceAvailableInRegion = async (region, instanceType) => {
    try {
        const pricingData = await loadPricingData();
        
        if (pricingData && pricingData.regions[region] && pricingData.regions[region].prices[instanceType]) {
            return true;
        }
        
        // If not in our data, assume it's available (will use estimation)
        return true;
    } catch (error) {
        console.error(`Error checking instance availability for ${instanceType} in ${region}:`, error);
        return true;
    }
};
